---
repos:
  # yamllint has trouble with scalars like '- lambda: |- '
  # - repo: https://github.com/google/yamlfmt
  #   rev: v0.10.0
  #   hooks:
  #     - id: yamlfmt
  - repo: local
    hooks:
      - id: esphome-openspool-mini
        name: ESPHome Validate Solo Config
        # entry: bash -c 'podman run -v "$(pwd)/firmware:/data" --rm ghcr.io/esphome/esphome:2024.11.0 config /data/openspool-mini.yaml'
        entry: esphome config firmware/openspool-mini.yaml
        language: system
        pass_filenames: false
        files: ^firmware/
      - id: esphome-openspool-ams
        name: ESPHome Validate AMS Config
        # entry: bash -c 'podman run -v "$(pwd)/firmware:/data" --rm ghcr.io/esphome/esphome:2024.11.0 config /data/openspool-ams.yaml'
        entry: esphome config firmware/openspool-ams.yaml
        language: system
        pass_filenames: false
        files: ^firmware/
