# Button is pin on the side of the ESP32s2
# Connected to pin 8
binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    internal: true
    state_topic:
    on_press:
      then:
        - light.turn_on:
            id: neopixel_light
            red: 0%
            green: 100%
            blue: 0%
        - delay: 0.5s
        - light.turn_on:
            id: neopixel_light
            effect: Data Upload
        - delay: 1s
        - light.turn_on:
            id: neopixel_light
            red: 0%
            green: 100%
            blue: 0%

    on_release:
      then:
        - logger.log: "Button 0 pressed"
        - script.execute: publish_filament_setting
        - light.turn_off:
            id: neopixel_light
