# Button is pin on the side of the ESP32s2
# Connected to pin 8
binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    internal: true
    state_topic:
    on_press:
      then:
        - light.turn_on:
            id: neopixel_light
            effect: Rainbow
            
        # - light.turn_off:
        #     id: neopixel_light
        # - light.turn_on:
        #     id: neopixel_light
        #     effect: none
        #     red: 0%
        #     green: 0%
        #     blue: 100%
        #     brightness: 100%

    on_release:
      then:
        - light.turn_on:
            id: neopixel_light
            brightness: 0%
            red: 0%
            green: 0%
            blue: 0%
        - delay: 50ms
        - light.turn_off:
            id: neopixel_light
        # - light.turn_on:
        #     id: neopixel_light
        #     red: 100%
        #     green: 0%
        #     blue: 0%
        #     brightness: 100%
