esphome:
  on_boot:
    then:
      - script.execute: set_led_rainbow
      - delay: 5s
      - script.execute: set_led_white
  on_shutdown:
    then:
      - script.execute: set_led_off

light:
  - platform: esp32_rmt_led_strip
    id: neopixel_light
    pin: GPIO16
    num_leds: 1
    rgb_order: GRB
    name: leds
    chipset: WS2812
    rmt_channel: 0
    default_transition_length: 0.4s
    restore_mode: ALWAYS_OFF
    state_topic:
    effects:
      - addressable_rainbow:
          name: Rainbow
          speed: 25
          width: 15
    #   - strobe:
    #       name: "Data Upload"
    #       colors:
    #         - state: TRUE
    #           brightness: 100%
    #           duration: 50ms
    #           red: 0%
    #           green: 100%
    #           blue: 0%
    #         - state: FALSE
    #           duration: 50ms

script:
  - id: set_led_red
    then:
      - light.turn_on:
          id: neopixel_light
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
  - id: set_led_green
    then:
      - light.turn_on:
          id: neopixel_light
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
  - id: set_led_blue
    then:
      - light.turn_on:
          id: neopixel_light
          effect: none
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
  - id: set_led_white
    then:
      - light.turn_on:
          id: neopixel_light
          effect: none
          red: 100%
          green: 100%
          blue: 100%
          brightness: 75%
  - id: set_led_off
    then:
      - light.turn_on:
          id: neopixel_light
          brightness: 0%
          red: 0%
          green: 0%
          blue: 0%
      - delay: 50ms
      - light.turn_off:
          id: neopixel_light
          transition_length: 0s
  - id: set_led_rainbow
    then:
      - light.turn_on:
          id: neopixel_light
          effect: Rainbow
