wifi:
  output_power: 10 # https://github.com/esphome/issues/issues/3988#issuecomment-1449954758
  ap:
    ssid: "OpenSpool"
  reboot_timeout: 0s
  power_save_mode: none
  # reboot_timeout: 15min
  # power_save_mode: LIGHT # Reduce to NONE if encountering issues with wifi connectivity
  #TODO: if it is in ap mode, then pulse blue
  # on_connect:
  #   then:
  #     - script.stop: set_led_rainbow
  #     - script.execute: 
  #         id: set_led_white
  #         led_number: -1
  #     - script.stop: set_led_white


sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    state_topic: # Don't post update to MQTT
    icon: mdi:wifi

text_sensor: 
  - platform: wifi_info
    # TODO: don't post to mqtt, static_topic isn't valid for wifi_info


# text_sensor:
#   # state_topic: # Don't post update to MQTT
#   # Get the WiFi details
#   - platform: wifi_info
#     ip_address:
#       name: ${name} IP Address
#       state_topic:
#     ssid:
#       name: ${name} SSID
#       state_topic:
#     mac_address:
#       name: ${name} Mac Address
#       state_topic:
