title: OpenSpool
description: Your filament wants to be free
theme: just-the-docs

# url: https://just-the-docs.github.io
url: https://openspool.io

aux_links:
  "Edit this page on Github": 
    - https://github.com/spuder/openspool

logo: "images/OpenSpoolLogoMedium1.png"

favicon: "images/favicon.ico"

color_scheme: dark


plugins:
  - jekyll-default-layout

head_scripts:
#https://github.com/esphome/esp-web-tools/issues/515#issuecomment-2387664391
  - https://unpkg.com/esp-web-tools@8.0.6/dist/web/install-button.js?module
  # - https://unpkg.com/@improv-wifi/sdk-serial@1.1.0/dist/serial.min.js?module


callouts:
  warning:
    title: Warning
    color: red
  note: 
    title: Note
    color: blue
  important:
    title: Important
    color: blue
  caution:
    title: Caution
    color: yellow
