substitutions:
  name: openspool
  version: "0.0.0" # Keep this at 0.0.0 as github-actions will modify this file at build time

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: spuder.openspool
    version: ${version}
    # on_update:
  min_version: 2024.10.1
  platformio_options:
    build_unflags: -std=gnu++11
    build_flags: 
      - -std=gnu++14
  on_boot:
    then:
      - script.execute: set_led_rainbow
      - delay: 3s
      - script.stop: set_led_rainbow
      - light.turn_on:
          id: neopixel_light
          effect: none
      - script.execute: set_all_leds_white
      # - script.execute: set_all_leds_white
      # - lambda: |-
      #     //TODO: this appears to have broken and no longer blinks blue
      #     if (!wifi::global_wifi_component->is_connected() && 
      #         wifi::global_wifi_component->wifi_soft_ap_ip().str() == "192.168.4.1") {
      #       id(set_led_breathing_blue).execute();
      #     }
      # - lambda: |-
      #     id(my_ota).set_auth_password("New password");
  on_shutdown:
    then:
      - script.execute: set_led_off

esp32:
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    # version: recommended
    # sdkconfig_options:
      # MBEDTLS_CERTIFICATE_BUNDLE: y
      # MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL: y

logger:

packages:
  # uptime: !include conf.d/uptime.yaml
  wifi: !include conf.d/wifi.yaml
  web_server: !include conf.d/web_server.yaml
  debug: !include conf.d/debug.yaml
  # time: !include conf.d/time.yaml
  status_led: !include conf.d/status_led.yaml
  mqtt_bambu_lan: !include conf.d/mqtt_bambu_lan.yaml
  button: !include conf.d/button.yaml
  filament: !include conf.d/filament.yaml
  bambu_printer: !include conf.d/bambu_printer.yaml
  pn532_rfid: !include conf.d/pn532_rfid.yaml
  automation: !include conf.d/automation.yaml
  leds: !include conf.d/leds.yaml
  # improv: !include conf.d/improv.yaml
  # update: !include conf.d/update.yaml
  # psram: !include conf.d/psram.yaml
