---
substitutions:
  hide_ams_sensors: 'true'
  led_pin: GPIO16
  spi2_type: SPI2 #SPI2,SPI3,any,hardware
  spi2_clk_pin: GPIO36
  spi2_miso_pin: GPIO37
  spi2_mosi_pin: GPIO35
  rfid0_spi_interface: SPI2
  rfid0_ss_pin: GPIO34
  #rfid1_spi_interface: SPI2
  #rfid1_clk_pin: GPIO21
  ## rfid1_spi_interface: SPI2
  ## rfid1_clk_pin: GPIO08
esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf
packages:
  base: !include common.yaml
  status_led: !include conf.d/status_led.yaml
  # ota-esphome: !include conf.d/ota-esphome.yaml #TODO: reenalbe ota-esphome, disabled to troubleshoot wb not loading
  button: !include conf.d/button.yaml

api: 
  reboot_timeout: 0s #reboot_timeout must be 0 if api and mqtt are defined
  id: api_openspool
dashboard_import:
  package_import_url: github://spuder/openspool/firmware/config-solo.yaml@main
  import_full_config: false