substitutions:
  rfid1_spi_interface: spi #any on Breadboard
  rfid1_clk_pin: GPIO36 #39 on Breadboard version
  rfid1_miso_pin: GPIO37
  rfid1_mosi_pin: GPIO35
  rfid1_ss_pin: GPIO34 #33 on Breadboard version

esp32:
  board: lolin_s2_mini
  variant: esp32s2

packages:
  base: !include common.yaml