substitutions:
  rfid1_spi_interface: spi2
  rfid1_clk_pin: GPIO36
  rfid1_miso_pin: GPIO37
  rfid1_mosi_pin: GPIO35
  rfid1_ss_pin: GPIO34
  hide_ams_sensors: 'false'

esp32:
  # board: esp32-s3-devkitc-1
  board: lolin_s2_mini
  framework: 
      type: esp-idf
  # variant: esp32s2
  # partitions:
  # framework: 
  #   type: esp-idf
  #   sdkconfig_options:
  #     CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: y
  #     CONFIG_ESP_TLS_USE_SECURE_ELEMENT: y
  #     # CONFIG_ESP_TLS_USE_DS_PERIPHERAL: y

packages:
  base: !include common.yaml
  ams: !include conf.d/ams.yaml
