substitutions:
  name: openspool
  version: "0.1.0" #TODO: ensure this is always set
  board: lolin_s2_mini
  variant: esp32s2
  rfid1_spi_interface: spi #any on Breadboard
  rfid1_clk_pin: GPIO36 #39 on Breadboard version
  rfid1_miso_pin: GPIO37
  rfid1_mosi_pin: GPIO35
  rfid1_ss_pin: GPIO34 #33 on Breadboard version

esphome:
  name: ${name} #Don't use underscore '_' in name https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  name_add_mac_suffix: true
  project:
    name: spuder.openspool
    version: ${version}
    # on_update:
  min_version: 2024.10.1
  platformio_options:
    # upload_speed: 115200 #TODO: This fails the first time no matter what
    build_unflags: -std=gnu++11
    build_flags: -std=gnu++14
    # upload_speed: 115200 # Wemos D1 Mini from Aliexpress struggle at 460800 baud rate
  on_boot:
    then:
      - script.execute: set_led_rainbow
      - delay: 3s
      - lambda: |-
          //TODO: this appears to have broken and no longer blinks blue
          if (!wifi::global_wifi_component->is_connected() && 
              wifi::global_wifi_component->wifi_soft_ap_ip().str() == "192.168.4.1") {
            id(set_led_breathing_blue).execute();
          }
      # - lambda: |-
      #     id(my_ota).set_auth_password("New password");
  on_shutdown:
    then:
      - script.execute: set_led_off

esp32:
  board: ${board}
  #variant: ${variant}
  framework:
    type: esp-idf
    version: recommended

logger:
# MQTT and api are not compatible: https://esphome.io/components/mqtt.html
# api:
#   reboot_timeout: 0s
# ota:

packages:
  uptime: !include conf.d/uptime.yaml
  wifi: !include conf.d/wifi.yaml
  web_server: !include conf.d/web_server.yaml
  #debug: !include conf.d/debug.yaml
  # time: !include conf.d/time.yaml
  status_led: !include conf.d/status_led.yaml
  mqtt_bambu_lan: !include conf.d/mqtt_bambu_lan.yaml
  button: !include conf.d/button.yaml
  filament: !include conf.d/filament.yaml
  bambu_printer: !include conf.d/bambu_printer.yaml
  rc532_rfid: !include conf.d/rc532_rfid.yaml
  automation: !include conf.d/automation.yaml
  leds: !include conf.d/leds.yaml
  #improv: !include conf.d/improv.yaml
  #ota: !include conf.d/ota.yaml
  # bambu_ams: !include conf.d/bambu_ams.yaml
