substitutions:
  name: rainbow-reel
  friendly_name: Rainbow Reel

esphome:
  name: ${name} #Don't use underscore '_' in name https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  friendly_name: ${friendly_name} #TODO: only used by home assistant, probably should remove
  name_add_mac_suffix: true
  # platformio_options:
  #   build_flags: 
  #     -D CONFIG_MQTT_TRANSPORT_SSL=0
  on_boot:
    then:
      - logger.log: "Booting ${friendly_name}"


esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf

logger:
# MQTT and api are not compatible: https://esphome.io/components/mqtt.html
# api:
#   reboot_timeout: 0s
# ota:

packages:
  uptime: !include conf.d/uptime.yaml
  wifi: !include conf.d/wifi.yaml
  web_server: !include conf.d/web_server.yaml
  debug: !include conf.d/debug.yaml
  # test: !include conf.d/test.yaml
  time: !include conf.d/time.yaml
  status_led: !include conf.d/status_led.yaml
  mqtt_bambu_lan: !include conf.d/mqtt_bambu_lan.yaml
  button: !include conf.d/button.yaml
  filament: !include conf.d/filament.yaml
  bambu_printer: !include conf.d/bambu_printer.yaml
  rc522_rfid: !include conf.d/rc522_rfid.yaml
