substitutions:
  rfid1_spi_interface: any
  rfid1_clk_pin: GPIO21
  rfid1_miso_pin: GPIO22
  rfid1_mosi_pin: GPIO23
  rfid1_ss_pin: GPIO25

esp32:
  board: esp32dev

packages:
  base: !include common.yaml