name: ESPHome Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create empty secrets file
        run: |
            touch firmware/secrets.yaml
            touch firmware/conf.d/secrets.yaml
      - name: Build ESPHome firmware
        uses: esphome/build-action@v4.0.2
        with:
          yaml-file: firmware/config.yaml
          release-summary: "Test"
          complete-manifest: true
      - name: List output files
        run: |
          ls -l
