name: ESPHome Build and Commit Manifest

on:
  push:
    branches: [main]
    paths:
      - 'firmware/**'          # Include all files in firmware/
      - '!firmware/manifest.json'  # Exclude manifest.json
      - '!firmware/*.bin'
      - .github/workflows/build.yaml #Include changes to this file
      - '!artifacts/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Create empty secrets file
        run: |
          touch firmware/secrets.yaml
          touch firmware/conf.d/secrets.yaml

      - name: Set git sha
        run: echo "RELEASE_SUMMARY=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      - name: Build ESPHome firmware
        uses: esphome/build-action@v4.0.2
        with:
          yaml-file: firmware/config.yaml
          release-summary: ${{ env.RELEASE_SUMMARY }}
          complete-manifest: true
          release-url: "https://raw.githubusercontent.com/spuder/OpenSpool/main/artifacts/openspool-esp32s2/manifest.json"

      - name: List output files
        run: |
          ls -l openspool-esp32s2

      - name: Copy manifest to artifacts folder
        run: |
          mkdir -p artifacts
          mv openspool-esp32s2 artifacts/
          for file in artifacts/openspool-esp32s2/*.bin; do
            md5sum "$file" | awk '{print $1}' > "${file}.md5"
            md5_length=$(wc -c < "${file}.md5")
            if [ "$md5_length" -ne 33 ]; then
              echo "MD5 generation failed for $file (length: $md5_length)"
              exit 1
            fi
          done
           

      - name: Commit manifest file
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com      
          message: Update manifest.json
          add: "artifacts/*"
          push: true

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: openspool-esp32s2-${{ github.sha }}
      #     path: |
      #       openspool-esp32s2/*.bin
      #       openspool-esp32s2/manifest.json
      #     retention-days: 90
  # cleanup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete old artifacts
  #       uses: c-hive/gha-remove-artifacts@v1
  #       with:
  #         age: '90 days'
  #         skip-recent: 5