name: ESPHome Build and Commit Manifest

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/manifest.json'
  pull_request:
    paths-ignore:
      - '**/manifest.json'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Create empty secrets file
        run: |
          touch firmware/secrets.yaml
          touch firmware/conf.d/secrets.yaml

      - name: Build ESPHome firmware
        uses: esphome/build-action@v4.0.2
        with:
          yaml-file: firmware/config.yaml
          release-summary: "Test" #TODO: change this to the commit message
          complete-manifest: true
          release-url: "https://raw.githubusercontent.com/spuder/OpenSpool/main/firmware/manifest.json"

      - name: List output files
        run: |
          ls -l openspool-esp32s2

      - name: Copy manifest to firmware folder
        run: |
          cp openspool-esp32s2/manifest.json firmware/manifest.json

      - name: Commit manifest file
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com      
          message: Update manifest.json
          add: "firmware/manifest.json"
          push: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openspool-esp32s2-${{ github.sha }}
          path: |
            openspool-esp32s2/*.bin
            openspool-esp32s2/manifest.json
          retention-days: 90
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '90 days'
          skip-recent: 5